# Generated by Django 4.2.4 on 2023-09-02 08:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('cityID', models.AutoField(primary_key=True, serialize=False)),
                ('cityName', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Properties',
            fields=[
                ('propertyID', models.AutoField(primary_key=True, serialize=False)),
                ('property_search_parameters', models.TextField()),
                ('address', models.CharField(max_length=255)),
                ('num_of_bedrooms', models.PositiveIntegerField()),
                ('num_of_bathrooms', models.PositiveIntegerField()),
                ('has_power_solutions', models.BooleanField()),
                ('has_water_solutions', models.BooleanField()),
                ('property_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('searchID', models.AutoField(primary_key=True, serialize=False)),
                ('search_parameters', models.TextField()),
                ('search_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Suburbs',
            fields=[
                ('suburbID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('coordinates', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.city')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PropertiesToBuy',
            fields=[
                ('properties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='MiBarrioApp.properties')),
                ('properties_buy_ID', models.AutoField(primary_key=True, serialize=False)),
                ('sale_price', models.PositiveIntegerField()),
            ],
            bases=('MiBarrioApp.properties',),
        ),
        migrations.CreateModel(
            name='PropertiesToRent',
            fields=[
                ('properties_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='MiBarrioApp.properties')),
                ('properties_rent_ID', models.AutoField(primary_key=True, serialize=False)),
                ('rental_price', models.PositiveIntegerField()),
            ],
            bases=('MiBarrioApp.properties',),
        ),
        migrations.CreateModel(
            name='SuburbStatistics',
            fields=[
                ('suburb_statsID', models.AutoField(primary_key=True, serialize=False)),
                ('crime_rate', models.PositiveIntegerField()),
                ('year', models.DateTimeField()),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.suburbs')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResults',
            fields=[
                ('search_resultID', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.searches')),
                ('suburb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.suburbs')),
            ],
        ),
        migrations.CreateModel(
            name='SearchProfile',
            fields=[
                ('search_profileID', models.AutoField(primary_key=True, serialize=False)),
                ('sp_name', models.TextField()),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('social_cultural', models.TextField()),
                ('health_wellness', models.TextField()),
                ('leisure_recreation', models.TextField()),
                ('community_services', models.TextField()),
                ('transportation_active', models.BooleanField()),
                ('transportation_public', models.BooleanField()),
                ('backup_power_supply', models.BooleanField()),
                ('backup_water_supply', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='searches',
            name='search_profileID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.searchprofile'),
        ),
        migrations.AddField(
            model_name='searches',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='properties',
            name='suburb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiBarrioApp.suburbs'),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('feedbackID', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('category', models.CharField(max_length=255)),
                ('message', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
