# Generated by Django 4.2.4 on 2023-09-05 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBarrioApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchprofile',
            old_name='community_services',
            new_name='community_services_tags',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='health_wellness',
            new_name='health_wellness_tags',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='leisure_recreation',
            new_name='leisure_recreation_tags',
        ),
        migrations.RenameField(
            model_name='searchprofile',
            old_name='social_cultural',
            new_name='social_cultural_tags',
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='community_services_levels',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='health_wellness_levels',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='leisure_recreation_levels',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='searchprofile',
            name='social_cultural_levels',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='searchprofile',
            name='age',
            field=models.TextField(),
        ),
    ]
