# Generated by Django 4.2.5 on 2023-09-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBarrioApp', '0003_rename_city_cities_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
