# Generated by Django 4.2.5 on 2023-09-26 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MiBarrioApp', '0005_customuser_groups_customuser_user_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='properties',
            name='address',
        ),
    ]
