# Generated by Django 4.2.5 on 2023-09-27 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBarrioApp', '0007_properties_search_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='properties',
            name='num_of_bathrooms',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='properties',
            name='num_of_bedrooms',
            field=models.FloatField(),
        ),
    ]
