# Generated by Django 4.2.5 on 2023-10-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiBarrioApp', '0009_properties_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='properties',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
